version: '3'

services:
  api:
    build: ./api
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.23
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=adonis_db